name: Free Interactive macOS Terminal
on: workflow_dispatch # Allows you to manually trigger it with a button

jobs:
  interactive-terminal:
    runs-on: macos-latest # Tells GitHub to give you a Mac server
    steps:
      - name: Setup Web VS Code Session
        uses: fawazahmed0/action-debug-vscode@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
